Repository Distributive-Network/PythonMonkey, pull requests merged in 2023-07, with the labels that each got.

#37 implement PyProxyHandler and JSObjectProxy
  CMakeLists.txt
  include/BoolType.hh
  include/BufferType.hh
  include/DateType.hh
  include/DictType.hh
  include/ExceptionType.hh
  include/FloatType.hh
  include/FuncType.hh
  include/IntType.hh
  include/JSObjectProxy.hh
  include/ListType.hh
  include/NoneType.hh
  include/NullType.hh
  include/PromiseType.hh
  include/PyEvaluator.hh
  include/PyProxyHandler.hh
  include/PyType.hh
  include/StrType.hh
  include/TupleType.hh
  include/modules/pythonmonkey/pythonmonkey.hh
  include/utilities.hh
  python/pythonmonkey/pythonmonkey.pyi
  src/BoolType.cc
  src/BufferType.cc
  src/DateType.cc
  src/DictType.cc
  src/ExceptionType.cc
  src/FloatType.cc
  src/FuncType.cc
  src/IntType.cc
  src/JSObjectProxy.cc
  src/ListType.cc
  src/NoneType.cc
  src/NullType.cc
  src/PromiseType.cc
  src/PyEvaluator.cc
  src/PyProxyHandler.cc
  src/StrType.cc
  src/TupleType.cc
  src/jsTypeFactory.cc
  src/modules/pythonmonkey/pythonmonkey.cc
  src/pyTypeFactory.cc
  tests/python/test_pythonmonkey_eval.py
Labels: enhancement, help wanted

#96 chore(git): ignore local `.venv` folder
  .gitignore
Labels: enhancement

#92 build(setup.sh): add missing pkgs on fresh ubuntu systems
  setup.sh
Labels: enhancement

#126 feature(pmjs): change and update pmjs to become cli tool
  README.md
  peter-jr
  pyproject.toml
  python/pythonmonkey/cli/__init__.py
  python/pythonmonkey/cli/pmjs.py
  python/pythonmonkey/lib/pmjs/global-init.js
  tests/js/commonjs-modules.bash
  tests/js/console-stdio.bash
  tests/js/pmjs-eopt.bash
  tests/js/pmjs-global-arguments.bash
  tests/js/pmjs-interactive-smoke.bash
  tests/js/pmjs-popt.bash
  tests/js/pmjs-require-cache.bash
  tests/js/pmjs-ropt.bash
Labels: enhancement

#97 Add templates for GitHub issues
  .github/ISSUE_TEMPLATE/bug_pythonmonkey.yaml
  .github/ISSUE_TEMPLATE/feature_pythonmonkey.yaml
Labels: documentation

#139 Make pmjs & peter-jr work on Windows
  .github/workflows/test-and-publish.yaml
  poetry.lock
  pyproject.toml
  python/pythonmonkey/cli/pmjs.py
  python/pythonmonkey/require.py
  tests/js/commonjs-modules.bash
  tests/js/console-stdio.bash
  tests/js/pmjs-eopt.bash
  tests/js/pmjs-global-arguments.bash
  tests/js/pmjs-interactive-smoke.bash
  tests/js/pmjs-popt.bash
  tests/js/pmjs-require-cache.bash
  tests/js/pmjs-ropt.bash
  tests/js/typeofs.simple
Labels: blocked
