Repository Distributive-Network/PythonMonkey, pull requests merged in 2024-06, with the labels that each got.

#354 Support HTTP-Keep-Alive in our `XMLHttpRequest` implementation
  python/pythonmonkey/builtin_modules/XMLHttpRequest-internal.py
  python/pythonmonkey/builtin_modules/XMLHttpRequest.js
  tests/js/xhr-http-keep-alive.bash
  tests/js/xhr.simple
Labels: release-blocker

#353 JSString Improvements
  Makefile
  include/JSStringProxy.hh
  include/StrType.hh
  include/jsTypeFactory.hh
  src/ExceptionType.cc
  src/JSObjectIterProxy.cc
  src/JSStringProxy.cc
  src/StrType.cc
  src/jsTypeFactory.cc
  src/modules/pythonmonkey/pythonmonkey.cc
  src/pyTypeFactory.cc
  src/setSpiderMonkeyException.cc
  tests/python/test_strings.py
Labels: bug, release-blocker

#361 fix python function arg-count mismatch frustration
  src/jsTypeFactory.cc
  tests/python/test_arrays.py
  tests/python/test_functions.py
Labels: enhancement
